/** Common country list for profile / signup. */
export const COUNTRIES = [
  "New Zealand",
  "Australia",
  "United States",
  "United Kingdom",
  "Canada",
  "Ireland",
  "Singapore",
  "Hong Kong",
  "Japan",
  "South Korea",
  "China",
  "India",
  "Indonesia",
  "Malaysia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Gurmany",
  "France",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Spain",
  "Italy",
  "Portugal",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "South Africa",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "Turkey",
  "Poland",
  "Czech Republic",
  "Austria",
  "Greece",
  "Fiji",
  "Samoa",
  "Tonga",
  "Papua New Guinea",
  "Other",
] as const;

export type CountryName = (typeof COUNTRIES)[number];
