#!/usr/bin/env node
/**
 * AetherForge Stox — Full-engine self-hosted runner.
 *
 * Uses the same market-intel engine as the AetherForge AI website.
 *
 * Usage:
 *   npm run report
 *   npm run report -- --portfolio ./my-portfolio.csv
 */

import { resolve } from "node:path";
import { loadPortfolio } from "./portfolio.js";
import { fetchQuotes, fetchHistories } from "./yahoo.js";
import { analyseHoldingFull } from "./analysis.js";
import { writeReport } from "./report.js";
import type { StoxReport, FullHoldingAnalysis } from "./types.js";

function parseArgs() {
  const args = process.argv.slice(2);
  let portfolioPath = "portfolio.csv";
  for (let i = 0; i < args.length; i++) {
    if ((args[i] === "--portfolio" || args[i] === "-p") && args[i + 1]) {
      portfolioPath = args[i + 1];
      i++;
    }
  }
  return { portfolioPath };
}

async function main() {
  console.log("\n⚡ AetherForge Stox — Full Engine (same core as the website)\n");

  const { portfolioPath } = parseArgs();
  const absPath = resolve(process.cwd(), portfolioPath);

  // 1. Load portfolio
  const holdings = loadPortfolio(absPath);
  const tickers = holdings.map((h) => h.ticker);

  // 2. Live quotes + real daily histories (when available)
  console.log("Fetching live quotes and price history…");
  const [quotes, histories] = await Promise.all([
    fetchQuotes(tickers),
    fetchHistories(tickers),
  ]);

  // 3. Full engine analysis on every holding
  const analyses: FullHoldingAnalysis[] = holdings.map((h) => {
    const q = quotes[h.ticker] ?? null;
    const hist = histories[h.ticker] ?? null;
    if (!q) {
      console.warn(`  ⚠ No live quote for ${h.ticker} — anchoring to average cost`);
    }
    if (hist) {
      console.log(`  ✓ ${h.ticker}: live price + real history (${hist.length} days)`);
    } else {
      console.log(`  · ${h.ticker}: live/anchor price + modelled series`);
    }
    return analyseHoldingFull(h, q, hist);
  });

  // 4. Portfolio summary
  const totalValue = analyses.reduce((s, a) => s + a.marketValue, 0);
  const totalCost = analyses.reduce((s, a) => s + a.costBasis, 0);
  const totalPnl = totalValue - totalCost;
  const totalPnlPct = totalCost > 0 ? (totalPnl / totalCost) * 100 : 0;

  const report: StoxReport = {
    generatedAt: new Date().toLocaleString("en-NZ", {
      weekday: "short",
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
    }),
    title: "Stox Intelligence Report — Full Engine",
    summary: {
      totalValue: Math.round(totalValue * 100) / 100,
      totalCost: Math.round(totalCost * 100) / 100,
      totalPnl: Math.round(totalPnl * 100) / 100,
      totalPnlPct: Math.round(totalPnlPct * 100) / 100,
      holdingsCount: analyses.length,
    },
    holdings: analyses,
    disclaimer:
      "This report is generated by the AetherForge Stox self-hosted package using the same technical-analysis engine that powers the AetherForge AI website. It provides informational market analysis only and is not personalised financial advice, a recommendation, or an offer to buy or sell any security. Always do your own research and consider seeking advice from a licensed financial adviser.",
  };

  // 5. Write HTML report
  const outPath = writeReport(report);
  console.log(`\n✅ Full-engine report generated: ${outPath}`);
  console.log(`   Open it in your browser to view the complete analysis.\n`);
}

main().catch((err) => {
  console.error("\n❌ Error:", err instanceof Error ? err.message : err);
  process.exit(1);
});
