"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Markdown } from "@/components/Markdown";
import { api } from "@/lib/api";
import { Sparkles, Loader2, RefreshCw, FileText } from "lucide-react";
import { toast } from "sonner";

export function AnalysisPanel({ holdingsCount }: { holdingsCount: number }) {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    if (holdingsCount === 0) {
      toast.error("Add at least one holding to generate a report.");
      return;
    }
    setLoading(true);
    console.log("[dashboard] Requesting AI analysis report…");
    const res = await api.post<{ report: string }>("/api/analysis", {});
    setLoading(false);
    if (res.ok && res.data?.report) {
      setReport(res.data.report);
    } else {
      console.error("[dashboard] Analysis failed:", res.error);
      toast.error("Could not generate the report. Please try again.");
    }
  }

  return (
    <div className="rounded-3xl border border-border/70 bg-card/50 p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary ring-1 ring-primary/20">
            <FileText className="size-5" />
          </span>
          <div>
            <h2 className="font-display text-lg font-bold">AI research report</h2>
            <p className="text-xs text-muted-foreground">
              A grounded analysis of your current holdings, powered by Aurum AI.
            </p>
          </div>
        </div>
        {report && (
          <Button variant="outline" size="sm" onClick={generate} disabled={loading}>
            {loading ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <RefreshCw className="mr-2 size-4" />
            )}
            Regenerate
          </Button>
        )}
      </div>

      {!report && (
        <div className="mt-6 flex flex-col items-center justify-center rounded-2xl border border-dashed border-border/70 bg-background/30 px-6 py-12 text-center">
          <span className="grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary">
            <Sparkles className="size-7" />
          </span>
          <p className="mt-4 max-w-sm text-sm text-muted-foreground">
            Generate an on-demand equity report covering allocation, risk, and outlook — tailored to
            your portfolio.
          </p>
          <Button onClick={generate} disabled={loading} className="mt-5 font-semibold shadow-glow">
            {loading ? (
              <>
                <Loader2 className="mr-2 size-4 animate-spin" /> Analyzing portfolio…
              </>
            ) : (
              <>
                <Sparkles className="mr-2 size-4" /> Generate report
              </>
            )}
          </Button>
        </div>
      )}

      {report && (
        <div className="mt-5 rounded-2xl border border-border/60 bg-background/30 p-6">
          <Markdown content={report} />
          <p className="mt-6 border-t border-border/50 pt-4 text-[11px] leading-relaxed text-muted-foreground">
            This report is generated by AI for informational purposes only and does not constitute
            financial advice. Always do your own research.
          </p>
        </div>
      )}
    </div>
  );
}
